#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ORG_NAME}}-peer{{PEER_NUM}}-tls-cert
  namespace: ${NS}
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - {{ORG_NAME}}-peer{{PEER_NUM}}
    - {{ORG_NAME}}-peer{{PEER_NUM}}.${NS}.svc.cluster.local
    - {{ORG_NAME}}-peer{{PEER_NUM}}.${DOMAIN}
    - {{ORG_NAME}}-peer{{PEER_NUM}}-gateway-svc
    - {{ORG_NAME}}-peer{{PEER_NUM}}-gateway-svc.${DOMAIN}
  ipAddresses:
    - 127.0.0.1
  secretName: {{ORG_NAME}}-peer{{PEER_NUM}}-tls-cert
  issuerRef:
    name: {{ORG_NAME}}-tls-cert-issuer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ORG_NAME}}-peer{{PEER_NUM}}-config
data:
  FABRIC_CFG_PATH: /var/hyperledger/fabric/config
  FABRIC_LOGGING_SPEC: "debug:cauthdsl,policies,msp,grpc,peer.gossip.mcs,gossip,leveldbhelper=info"
  CORE_PEER_TLS_ENABLED: "true"
  CORE_PEER_TLS_CERT_FILE: /var/hyperledger/fabric/config/tls/tls.crt
  CORE_PEER_TLS_KEY_FILE: /var/hyperledger/fabric/config/tls/tls.key
  CORE_PEER_TLS_ROOTCERT_FILE: /var/hyperledger/fabric/config/tls/ca.crt
  CORE_PEER_ID: {{ORG_NAME}}-peer{{PEER_NUM}}.{{ORG_NAME}}.example.com
  CORE_PEER_ADDRESS: {{ORG_NAME}}-peer{{PEER_NUM}}:7051
  CORE_PEER_LISTENADDRESS: 0.0.0.0:7051
  CORE_PEER_CHAINCODEADDRESS: {{ORG_NAME}}-peer{{PEER_NUM}}:7052
  CORE_PEER_CHAINCODELISTENADDRESS: 0.0.0.0:7052
  # bootstrap peer is the other peer in the same org
  CORE_PEER_GOSSIP_BOOTSTRAP: {{ORG_NAME}}-peer2:7051
  CORE_PEER_GOSSIP_EXTERNALENDPOINT: {{ORG_NAME}}-peer{{PEER_NUM}}.${NS}.svc.cluster.local:7051
  CORE_PEER_LOCALMSPID: {{ORG_NAME}}MSP
  CORE_PEER_MSPCONFIGPATH: /var/hyperledger/fabric/organizations/peerOrganizations/{{ORG_NAME}}.example.com/peers/{{ORG_NAME}}-peer{{PEER_NUM}}.{{ORG_NAME}}.example.com/msp
  CORE_OPERATIONS_LISTENADDRESS: 0.0.0.0:9443
  CORE_PEER_FILESYSTEMPATH: /var/hyperledger/fabric/data/{{ORG_NAME}}-peer{{PEER_NUM}}.{{ORG_NAME}}.example.com
  CORE_LEDGER_SNAPSHOTS_ROOTDIR: /var/hyperledger/fabric/data/{{ORG_NAME}}-peer{{PEER_NUM}}.{{ORG_NAME}}.example.com/snapshots
  CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG: "{\"peername\":\"{{ORG_NAME}}peer{{PEER_NUM}}\"}"
  FABRIC_K8S_BUILDER_OBJECT_NAME_PREFIX: {{ORG_NAME}}-peer{{PEER_NUM}}-cc
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB
  CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP: "20"
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: localhost:5984
  CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME: admin
  CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD: adminpw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORG_NAME}}-peer{{PEER_NUM}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORG_NAME}}-peer{{PEER_NUM}}
  template:
    metadata:
      labels:
        app: {{ORG_NAME}}-peer{{PEER_NUM}}
        org: {{ORG_NAME}}
    spec:
      containers:
        - name: main
          image: ${FABRIC_PEER_IMAGE}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ORG_NAME}}-peer{{PEER_NUM}}-config
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 9443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config
            - name: tls-cert-volume
              mountPath: /var/hyperledger/fabric/config/tls
              readOnly: true
        - name: couchdb
          image: couchdb:${COUCHDB_VERSION}
          imagePullPolicy: IfNotPresent
          env:
            - name: "COUCHDB_USER"
              value: "admin" 
            - name: "COUCHDB_PASSWORD"
              value: "adminpw"
          ports:
              - containerPort: 5984
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-{{ORG_NAME}}
        - name: fabric-config
          configMap:
            name: {{ORG_NAME}}-config
        - name: tls-cert-volume
          secret:
            secretName: {{ORG_NAME}}-peer{{PEER_NUM}}-tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: {{ORG_NAME}}-peer{{PEER_NUM}}
spec:
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
    - name: chaincode
      port: 7052
      protocol: TCP
    - name: operations
      port: 9443
      protocol: TCP
  selector:
    app: {{ORG_NAME}}-peer{{PEER_NUM}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ORG_NAME}}-peer-gateway-svc
spec:
  ports:
    - name: grpc
      port: 7051
      protocol: TCP
  selector:
    org: {{ORG_NAME}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  labels:
    app: {{ORG_NAME}}-peer{{PEER_NUM}}
  name: {{ORG_NAME}}-peer{{PEER_NUM}}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ORG_NAME}}-peer{{PEER_NUM}}.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: {{ORG_NAME}}-peer{{PEER_NUM}}
                port:
                  name: grpc
            path: /
            pathType: ImplementationSpecific
    - host: {{ORG_NAME}}-peer-gateway-svc.${DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: {{ORG_NAME}}-peer-gateway-svc
                port:
                  name: grpc
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ORG_NAME}}-peer{{PEER_NUM}}.${DOMAIN}
    - hosts:
        - {{ORG_NAME}}-peer-gateway-svc.${DOMAIN}
