ENB_NETWOK_NAME=bank
ENV_CLUSTER_NAME=bank-cluster
ENV_DOMAIN=localho.st
ENV_CHANNEL_NAME=mychannel
ENV_ORG_NAMES="bank-org land-org"
ENV_NUM_PEERS_PER_ORG=2
ENV_ORDERER_NAME=orderer
ENV_NUM_ORDERERS=3

